services:
  whmanagement:
    build: ./WHManagement
    container_name: whmanagement
    depends_on:
      - db
      - mongodb
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dudemif
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_RABBITMQ_HOST: rabbitmq
  db:
    container_name: postgresWH
    image: postgres
    environment:
      POSTGRES_USER: rootUser
      POSTGRES_PASSWORD: pass-123
      POSTGRES_DB: dudemif
      PGDATA: /data/postgres

    ports:
      - "5432:5432"

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmqWH
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
